<?php

namespace Tests\Unit;

use App\Fixture;
use App\League;
use App\Team;
use Carbon\Carbon;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class FixtureTest extends TestCase
{
    use DatabaseMigrations;
    public $fixture;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->fixture = factory(Fixture::class)->create();
    }

    /** @test */
    public function a_fixture_belongs_to_a_league()
    {
        $this->assertInstanceOf(League::class, $this->fixture->league);
    }

    /** @test */
    public function a_fixture_has_a_event_date()
    {
        $this->assertInstanceOf(Carbon::class, $this->fixture->event_date);
    }

    /** @test */
    public function a_fixture_has_a_start_date_for_first_half()
    {
        $this->assertInstanceOf(Carbon::class, $this->fixture->first_half_start_at);
    }

    /** @test */
    public function a_fixture_has_a_start_date_for_secodn_half()
    {
        $this->assertInstanceOf(Carbon::class, $this->fixture->second_half_start_at);
    }

    /** @test */
    public function has_a_round()
    {
        $this->assertArrayHasKey('round', $this->fixture->toArray());
    }

    /** @test */
    public function has_a_status()
    {
        $this->assertArrayHasKey('status', $this->fixture->toArray());
    }

    /** @test */
    public function has_a_elapsed()
    {
        $this->assertArrayHasKey('elapsed', $this->fixture->toArray());
    }

    /** @test */
    public function has_a_venue()
    {
        $this->assertArrayHasKey('venue', $this->fixture->toArray());
    }

    /** @test */
    public function has_a_home_team()
    {
        $this->assertInstanceOf(Team::class, $this->fixture->homeTeam);
    }

    /** @test */
    public function has_a_away_team()
    {
        $this->assertInstanceOf(Team::class, $this->fixture->awayTeam);
    }

    /** @test */
    public function has_goals_home_team()
    {
        $this->assertArrayHasKey('goals_home_team', $this->fixture->toArray());
    }

    /** @test */
    public function has_goals_away_team()
    {
        $this->assertArrayHasKey('goals_away_team', $this->fixture->toArray());
    }

    /** @test */
    public function has_score_half_time()
    {
        $this->assertArrayHasKey('score_half_time', $this->fixture->toArray());
    }

    /** @test */
    public function has_score_full_time()
    {
        $this->assertArrayHasKey('score_full_time', $this->fixture->toArray());
    }

    /** @test */
    public function has_score_extra_time()
    {
        $this->assertArrayHasKey('score_extra_time', $this->fixture->toArray());
    }

    /** @test */
    public function has_score_penalty()
    {
        $this->assertArrayHasKey('score_penalties', $this->fixture->toArray());
    }



}
