<?php

namespace Tests\Unit;

use App\Country;
use App\League;
use App\Season;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class LeagueTest extends TestCase
{
    use DatabaseMigrations;

    public $league;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->league = factory(League::class)->create();
    }

    /** @test */
    public function a_league_has_a_name()
    {
        $this->assertNotEmpty($this->league->name);
    }

    /** @test */
    public function a_league_can_have_a_country()
    {
        $league = factory(League::class)->create(['country_id'=>factory(Country::class)->create()->id]);

        $this->assertInstanceOf(Country::class, $league->country);

    }
    /** @test */
    public function a_league_has_many_seasons()
    {
        $season = factory(Season::class)->create();
        $this->league->seasons()->sync([$season->id]);
        $this->assertInstanceOf(Season::class, $this->league->seasons->first());
    }

}
