<?php

namespace Tests\Unit;

use App\Country;
use App\Team;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class TeamTest extends TestCase
{
    use DatabaseMigrations;

    public $team;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->team = factory(Team::class)->create();
    }

    /** @test */
    public function a_team_belongs_to_country()
    {
        $this->assertInstanceOf(Country::class, $this->team->country);
    }

    /** @test */
    public function a_team_has_a_name()
    {
        $this->assertArrayHasKey('name', $this->team->toArray());
    }

    /** @test */
    public function a_team_has_a_code()
    {
        $this->assertArrayHasKey('code', $this->team->toArray());
    }
}
